### ISSUE TITLE
Could you log the midi output of playtron please?

### ISSUE THREAD

**Issue by inktrap** [avielbr/playtronica-tools#3]
Hi! I was just wondering if you could log the midi output of the playtron so that I have a clearer picture how I would have to remap it to work with e.g. a volca fm. The playtronica website just says that the names of the notes are on the back.

**Comment by avibrown** [comment]
Hi, do I understand correctly that you're interested in knowing which one of the Playtron contacts was activated?

Unfortunately my Playtron died, so I don't have a way of testing this at the moment :(

**Comment by inktrap** [comment]
Hi Avi,

owh I am sorry to hear that. Yeah I would like the midi data for each contact activation. But tbh during the last time I did a lot of research and started two other musical projects which are based on DIY electronics.

If you liked your playtron but want to tinker a bit you may found this interesting: <https://www.adafruit.com/product/2024> With an arduino and the capacitive touch shield and some crocodile clips, that you already have, you can build your own playtron pretty easily … you can play twelve notes with it, which is one octave. Given that the shield is 12$ and the arduino uno is even cheaper if you order it made by a third-party (like 10$ with a breadboard aso.) it would be even cheaper.

Have a nice day :)
